version: '3.9'
services:
  typoteka.account.mongo:
    image: mongo:4.4
    restart: always
    container_name: typoteka.account.mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - 27017:27017
    volumes:
      - typoteka.mongo.account:/data/db
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mongo --eval ''db.adminCommand("ping")'' -u ${MONGO_USER} -p ${MONGO_PASSWORD} --authenticationDatabase admin',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  typeoteka.user.mongo.ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: typeoteka.user.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@typoteka.account.mongo:${MONGO_PORT}/
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:8081 || exit 1']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

volumes:
  typoteka.mongo.account:
